
package multispecility_hospital_solapur.DATA_TABLES;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import multispecility_hospital_solapur.use.GetConnection;

public class PATIENTS extends javax.swing.JFrame {

   
    public PATIENTS() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        try{
           DefaultTableModel  table = (DefaultTableModel)PATIENTSDATA.getModel();
           System.out.println("Inside the pati");
            String query = "SELECT * FROM VHSHOSPITAL.APPOINTMENTS";
            Statement statement = new GetConnection().Connect_mysql();
            ResultSet result = statement.executeQuery(query);
            
           while(result.next()){
               String Data[]={
              
                   result.getString("SR"),
                   result.getString("PID"),
                   result.getString("FNAME"), 
                   result.getString("MNAME"),
                   result.getString("LNAME"),

                   result.getString("AGE"),
                   result.getString("GENDER"),

                   result.getString("DOB"),
                   result.getString("MSTATUS"),
                   result.getString("CONTACT1"),
                   result.getString("CONTACT2"),
                   result.getString("AADHAARNO"), 
                   result.getString("PANNO"),
                   result.getString("DRNAME"),
                   result.getString("FEE"),
                   result.getString("OPDNO"),
              
                   result.getString("SYMPTOMS"),
                   result.getString("ADDRESS"),
                   result.getString("CITY"),
                   result.getString("DISTRICT"),
                   result.getString("STATE"),
                   result.getString("COUNTRY"),
                   result.getString("PINCODE"),
                   
                   result.getString("TIME"),
                   result.getString("DATE")};
              
//               SR,PID,FNAME,MNAME,LNAME,AGE,GENDER,DOB,MSTATUS,CONTACT1,CONTACT2,AADHAARNO,PANNO,DRNAME,FEE,OPDNO,SYMPTOMS,ADDRESS,CITY,DISTRICT,STATE,COUNTRY,PINCODE,DATE,TIME
                
                table.addRow(Data);
           } 
        }catch(Exception e){
            
        }
    }
    
public void search(String str){
        DefaultTableModel model = (DefaultTableModel) PATIENTSDATA.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        PATIENTSDATA.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PATIENTSDATA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_search.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton1.setText("Search Patients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PATIENTSDATA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SR", "PID", "FIRST NAME", "MIDDLE NAME", "LAST NAME", "AGE", "GENDER", "DATE OF BIRTH", "MSTATUS", "CONTACT1", "CONTACT2", "AADHAAR NO", "PAN NO", "DR NAME", "OPD NO", "FEE", "SYSMPTOMS", "ADDRESS", "CITY", "DISTRICT", "STATE", "COUNTRY", "PINCODE", "DATE", "TIME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PATIENTSDATA.setGridColor(new java.awt.Color(145, 178, 224));
        jScrollPane1.setViewportView(PATIENTSDATA);
        if (PATIENTSDATA.getColumnModel().getColumnCount() > 0) {
            PATIENTSDATA.getColumnModel().getColumn(0).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(0).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(1).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(1).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(2).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(2).setPreferredWidth(110);
            PATIENTSDATA.getColumnModel().getColumn(3).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(3).setPreferredWidth(110);
            PATIENTSDATA.getColumnModel().getColumn(4).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(4).setPreferredWidth(110);
            PATIENTSDATA.getColumnModel().getColumn(5).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(5).setPreferredWidth(30);
            PATIENTSDATA.getColumnModel().getColumn(6).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(6).setPreferredWidth(30);
            PATIENTSDATA.getColumnModel().getColumn(7).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(7).setPreferredWidth(40);
            PATIENTSDATA.getColumnModel().getColumn(8).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(8).setPreferredWidth(20);
            PATIENTSDATA.getColumnModel().getColumn(9).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(9).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(10).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(10).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(11).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(11).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(12).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(13).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(13).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(14).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(14).setPreferredWidth(20);
            PATIENTSDATA.getColumnModel().getColumn(15).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(15).setPreferredWidth(20);
            PATIENTSDATA.getColumnModel().getColumn(16).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(17).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(17).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(18).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(18).setPreferredWidth(60);
            PATIENTSDATA.getColumnModel().getColumn(19).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(19).setPreferredWidth(30);
            PATIENTSDATA.getColumnModel().getColumn(20).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(20).setPreferredWidth(30);
            PATIENTSDATA.getColumnModel().getColumn(21).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(21).setPreferredWidth(30);
            PATIENTSDATA.getColumnModel().getColumn(22).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(22).setPreferredWidth(20);
            PATIENTSDATA.getColumnModel().getColumn(23).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(23).setPreferredWidth(20);
            PATIENTSDATA.getColumnModel().getColumn(24).setResizable(false);
            PATIENTSDATA.getColumnModel().getColumn(24).setPreferredWidth(30);
        }

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 3, 18)); // NOI18N
        jLabel1.setText("PATIENTS    DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1919, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(404, 404, 404)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String af = txt_search.getText();
        search(af);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PATIENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PATIENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PATIENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PATIENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PATIENTS().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PATIENTSDATA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
